import{useEffect,useMemo,useState}from'react';
import{App as AntApp,Avatar,Badge,Button,Card,Col,Descriptions,Drawer,Empty,Form,Input,InputNumber,Layout,Menu,Modal,Progress,Row,Select,Space,Statistic,Table,Tag,Typography}from'antd';
import{AuditOutlined,CheckOutlined,DownloadOutlined,HomeOutlined,LogoutOutlined,PhoneOutlined,PlusOutlined,ProductOutlined,SearchOutlined,SettingOutlined,TeamOutlined}from'@ant-design/icons';
import type{CatalogItem,FollowUp,Lead,LeadStatus,OpeningProject,Recommendation,Role,StaffAccount,VenueType}from'@opening/shared';
import{leadStatusLabels,prototypeMeta,quadrantMeta,statusLabels}from'@opening/shared';
import{api,clearToken,downloadExcel,getToken}from'./api';
import LoginPage from'./LoginPage';
const{Sider,Header,Content}=Layout;const{Title,Text}=Typography;const statusColor:Record<string,string>={draft:'default',submitted:'blue',assigned:'cyan',planning:'gold',review:'orange',published:'green',foundation_confirmed:'lime',growth_active:'purple'};

const roleLabel:Record<Role,string>={admin:'管理员',consultant:'顾问',customer:'客户'};
const roleColor:Record<Role,string>={admin:'red',consultant:'blue',customer:'default'};

function App(){const{message}=AntApp.useApp();
  const[staff,setStaff]=useState<StaffAccount|null>(null);
  const[page,setPage]=useState('projects');
  const[projects,setProjects]=useState<OpeningProject[]>([]);
  const[leads,setLeads]=useState<Lead[]>([]);
  const[catalog,setCatalog]=useState<CatalogItem[]>([]);
  const[venues,setVenues]=useState<VenueType[]>([]);
  const[selected,setSelected]=useState<OpeningProject>();
  const[selectedLead,setSelectedLead]=useState<Lead>();
  const[query,setQuery]=useState('');
  const[loading,setLoading]=useState(false);
  const[authChecked,setAuthChecked]=useState(false);
  const role:Role=staff?.role||'admin';

  useEffect(()=>{const t=getToken();if(!t){setAuthChecked(true);return;}api('/auth/staff/me').then(function(s){setStaff(s);}).catch(function(){clearToken();}).finally(function(){setAuthChecked(true);});},[]);

  const load=async()=>{setLoading(true);try{const b=await api('/bootstrap') as any;setProjects(b.projects);setVenues(b.venues);if(['admin','consultant'].includes(role)){const c=await api('/catalog') as any;setCatalog(c);}if(['admin','consultant'].includes(role)){const l=await api('/leads') as any;setLeads(l);}}catch(e){message.error((e as Error).message)}finally{setLoading(false)}};
  useEffect(()=>{if(staff)load();},[staff]);const stats=useMemo(()=>{const active=projects.filter(p=>!['foundation_confirmed','growth_active'].includes(p.status)).length;const review=projects.filter(p=>p.status==='review').length;const pipeline=leads.reduce((s,l)=>s+(l.expectedAmount||l.quoteAmount||0),0);const unassignedLeads=leads.filter(l=>!l.assignedConsultantId).length;const myLeads=leads.filter(l=>l.assignedConsultantId===staff?.id&&l.status!=='won'&&l.status!=='lost').length;return{active,review,pipeline,unassignedLeads,myLeads};},[projects,leads,staff]);
  const action=async(path:string,body?:unknown,method='POST')=>{try{await api(path,{method,body:body?JSON.stringify(body):undefined});message.success('操作已完成');setSelected(undefined);setSelectedLead(undefined);load()}catch(e){message.error((e as Error).message)}};

  const canViewLeads=['admin','consultant'].includes(role);
  const canViewCatalog=['admin','consultant'].includes(role);
  const canViewVenues=role==='admin';
  const menuItems=[
    {key:'projects',icon:<HomeOutlined/>,label:'开馆项目'},
    ...(canViewLeads?[{key:'leads',icon:<TeamOutlined/>,label:'销售线索'}]:[]),
    ...(canViewCatalog?[{key:'catalog',icon:<ProductOutlined/>,label:'产品与价格'}]:[]),
    ...(canViewVenues?[{key:'venues',icon:<SettingOutlined/>,label:'运营原型'}]:[]),
    {key:'audit',icon:<AuditOutlined/>,label:'审核记录'},
  ];

  const handleLogout=()=>{clearToken();setStaff(null);setPage('projects');};
  const handleLogin=(s:StaffAccount)=>{setStaff(s);};

  if(!authChecked)return null;
  if(!staff)return <AntApp><LoginPage onLogin={handleLogin}/></AntApp>;

  return <Layout className="shell"><Sider width={248}className="sider"><div className="brand"><div className="brand-mark">衡</div><div><b>开馆助手</b><span>REHAB OPENING OS</span></div></div><Menu theme="dark"selectedKeys={[page]}onClick={e=>setPage(e.key)}items={menuItems}/><div className="side-foot"><span>当前工作空间</span><b>健衡开馆服务中心</b></div></Sider><Layout><Header className="topbar"><div><Text type="secondary">报价、审核与成交跟进</Text><Title level={4}>开馆服务工作台</Title></div><Space><Tag color={roleColor[role]}>{roleLabel[role]}</Tag><Avatar className="avatar">{staff.name[0]}</Avatar><Button type="text"icon={<LogoutOutlined/>}onClick={handleLogout}>退出</Button></Space></Header><Content className="content">
  {page==='projects'&&<ProjectPage projects={projects}loading={loading}query={query}setQuery={setQuery}stats={stats}role={role}onOpen={setSelected}/>} {page==='leads'&&canViewLeads&&<LeadPage leads={leads}loading={loading}query={query}setQuery={setQuery}onOpen={setSelectedLead}/>} {page==='catalog'&&canViewCatalog&&<CatalogPage items={catalog}venues={venues}role={role}onSaved={load}/>} {page==='venues'&&canViewVenues&&<VenuePage items={venues}/>} {page==='audit'&&<Card className="panel"><Empty description="在具体项目中查看报价版本、联系方式访问和状态变更记录"/></Card>}
  </Content></Layout><ProjectDrawer project={selected}role={role}onClose={()=>setSelected(undefined)}onAction={action}/><LeadDrawer lead={selectedLead}projects={projects}role={role}onClose={()=>setSelectedLead(undefined)}onAction={action}/></Layout>}

function ProjectPage({projects,loading,query,setQuery,stats,role,onOpen}:{projects:OpeningProject[];loading:boolean;query:string;setQuery:(x:string)=>void;stats:any;role:Role;onOpen:(x:OpeningProject)=>void}){return <><section className="intro"><div><span className="eyebrow">OPENING PIPELINE</span><Title>从门店定位，<em>走到正式成交。</em></Title><Text>四象限诊断、运营原型、装修建议和设备报价共享同一份客户档案。</Text></div><div className="trajectory"><div><span>注册</span><i style={{height:'88%'}}/></div><div><span>测算</span><i style={{height:'72%'}}/></div><div><span>报价</span><i style={{height:'55%'}}/></div><div><span>成交</span><i style={{height:'32%'}}/></div></div></section><Row gutter={14}className="stats"><Col span={6}><Card><Statistic title="进行中项目"value={stats.active}suffix="个"/></Card></Col><Col span={6}><Card><Statistic title="等待审核"value={stats.review}suffix="个"/></Card></Col>{role==='admin'&&<><Col span={6}><Card><Statistic title="待分配线索"value={stats.unassignedLeads}suffix="条"/></Card></Col><Col span={6}><Card><Statistic title="销售管道"value={stats.pipeline/10000}precision={1}suffix="万元"/></Card></Col></>}
{role==='consultant'&&<><Col span={6}><Card><Statistic title="我的跟进中线索"value={stats.myLeads}suffix="条"/></Card></Col><Col span={6}><Card><Statistic title="销售管道"value={stats.pipeline/10000}precision={1}suffix="万元"/></Card></Col></>}</Row><Card className="panel"title="开馆项目"extra={<Input prefix={<SearchOutlined/>}placeholder="搜索客户、城市、定位"value={query}onChange={e=>setQuery(e.target.value)}allowClear/>}><Table loading={loading}rowKey="id"dataSource={projects.filter(p=>[p.customerName,p.city,p.venueTypeName].join('').includes(query))}onRow={r=>({onClick:()=>onOpen(r)})}columns={[{title:'客户 / 项目',render:(_,p)=><div className="client"><Avatar>{p.customerName[0]}</Avatar><div><b>{p.customerName}</b><span>{p.city} · {p.venueTypeName}</span></div></div>},{title:'能力坐标',render:(_,p)=><Space><Tag color="geekblue">专业 {p.capabilityResult.technicalScore}</Tag><Tag color="green">商业 {p.capabilityResult.commercialScore}</Tag></Space>},{title:'规模',render:(_,p)=><><b>{p.area}㎡</b><div className="muted">预算 {(p.budget/10000).toFixed(0)} 万</div></>},{title:'标准版报价',render:(_,p)=>`¥${(p.quoteSummaries.find(x=>x.tier==='standard')?.total||0).toLocaleString()}`},{title:'当前阶段',dataIndex:'status',render:s=><Tag color={statusColor[s]}>{statusLabels[s as keyof typeof statusLabels]}</Tag>}]}/></Card></>}

function LeadPage({leads,loading,query,setQuery,onOpen}:{leads:Lead[];loading:boolean;query:string;setQuery:(x:string)=>void;onOpen:(x:Lead)=>void}){return <Card className="panel"title="销售线索与跟进"extra={<Input prefix={<SearchOutlined/>}placeholder="搜索姓名、手机号、城市"value={query}onChange={e=>setQuery(e.target.value)}allowClear/>}><Table loading={loading}rowKey="id"dataSource={leads.filter(l=>[l.name,l.phone,l.city,l.email].join('').includes(query))}onRow={r=>({onClick:()=>onOpen(r)})}columns={[{title:'客户',render:(_,l)=><div className="client"><Avatar>{l.name[0]}</Avatar><div><b>{l.name}</b><span>{l.phone.replace(/(\d{3})\d{4}(\d{4})/,'$1****$2')} · {l.city}</span></div></div>},{title:'阶段',dataIndex:'status',render:s=><Tag color={s==='won'?'green':s==='lost'?'red':'blue'}>{leadStatusLabels[s as LeadStatus]}</Tag>},{title:'意向',render:(_,l)=><>{l.quadrant?<b>{quadrantMeta[l.quadrant].name}</b>:'待测算'}<div className="muted">{l.prototype?prototypeMeta[l.prototype].name:'未定位'}</div></>},{title:'计划投入',dataIndex:'budget',render:v=>v?`${v/10000}万`:'待填写'},{title:'报价',dataIndex:'quoteAmount',render:v=>v?`¥${v.toLocaleString()}`:'—'},{title:'负责顾问',dataIndex:'assignedConsultantId',render:v=>v?<Tag color="green">{v}</Tag>:<Tag>待分配</Tag>},{title:'下次跟进',dataIndex:'nextFollowUpAt',render:v=>v?new Date(v).toLocaleString('zh-CN'):'未安排'}]}/></Card>}

function ProjectDrawer({project,role,onClose,onAction}:{project?:OpeningProject;role:Role;onClose:()=>void;onAction:(p:string,b?:unknown,m?:string)=>void}){const[recs,setRecs]=useState<Recommendation[]>([]);useEffect(()=>setRecs(project?.recommendations||[]),[project]);if(!project)return null;const canPublish=role==='admin'&&['review','submitted'].includes(project.status);const canPlan=['consultant','admin'].includes(role)&&['assigned','planning','published','review'].includes(project.status);const canAssign=role==='admin'&&project.status==='submitted';return <Drawer width={760}open onClose={onClose}title={<Space><span>{project.customerName}的开馆档案</span><Tag color={statusColor[project.status]}>{statusLabels[project.status]}</Tag></Space>}extra={<Space>{canAssign&&<Button onClick={()=>onAction(`/projects/${project.id}/assign`,{consultantId:'staff-consultant'})}>分配顾问</Button>}{canPlan&&<Button onClick={()=>onAction(`/projects/${project.id}/review`)}>提交审核</Button>}{canPublish&&<Button type="primary"icon={<CheckOutlined/>}onClick={()=>onAction(`/projects/${project.id}/publish`)}>审核发布</Button>}{['published','foundation_confirmed','growth_active'].includes(project.status)&&<Button icon={<DownloadOutlined/>}onClick={()=>downloadExcel(project.id)}>下载Excel</Button>}</Space>}><div className="drawer-score"><Progress type="circle"percent={project.capabilityResult.technicalScore}strokeColor="#1d7664"/><div><span>门店定位</span><h2>{quadrantMeta[project.quadrant].name} / {prototypeMeta[project.prototype.primary].name}</h2><p>专业 {project.capabilityResult.technicalScore} · 商业 {project.capabilityResult.commercialScore} · 投资准备度 {project.readinessScore}</p></div></div><Descriptions column={2}className="details"items={[{label:'城市',children:project.city},{label:'面积',children:`${project.area}㎡`},{label:'预算',children:`${project.budget/10000}万元`},{label:'计划开馆',children:project.openingDate},{label:'装修定位',children:project.renovation.keywords.join('、'),span:2},{label:'目标客群',children:project.audiences.join('、'),span:2}]}/><Title level={4}style={{marginTop:24}}>设备报价建议</Title>{recs.filter(r=>r.kind==='equipment').length?<Table rowKey="id"dataSource={recs.filter(r=>r.kind==='equipment')}pagination={false}size="small"columns={[{title:'设备',dataIndex:'name'},{title:'数量',dataIndex:'quantity',width:60},{title:'单价',dataIndex:'unitPrice',render:v=>v?`¥${v.toLocaleString()}`:'—',width:100},{title:'状态',dataIndex:'priceStatus',render:s=><Tag color={s==='approved'?'green':s==='conflict'?'red':'orange'}>{s==='approved'?'已审核':s==='conflict'?'冲突':'询价'}</Tag>,width:80}]}/>:<Empty description="暂无设备报价" image={Empty.PRESENTED_IMAGE_SIMPLE}/>}</Drawer>}

function LeadDrawer({lead,projects,role,onClose,onAction}:{lead?:Lead;projects:OpeningProject[];role:Role;onClose:()=>void;onAction:(p:string,b?:unknown,m?:string)=>void}){const[form]=Form.useForm();const[follow,setFollow]=useState<FollowUp[]>([]);useEffect(()=>{if(lead)api(`/leads/${lead.id}/follow-ups`).then(function(d){setFollow(d);}).catch(function(){setFollow([]);});},[lead]);if(!lead)return null;const linkedProject=projects.find(p=>p.id===lead.projectId);const canAssign=role==='admin'&&!lead.assignedConsultantId;return <Drawer width={620}open onClose={onClose}title={<Space><PhoneOutlined/><span>{lead.name} · 顾问跟进</span></Space>}extra={canAssign&&<Button type="primary"onClick={()=>onAction(`/leads/${lead.id}/assign`,{consultantId:'staff-consultant'})}>分配给当前顾问</Button>}><Descriptions column={2}items={[{label:'手机号',children:lead.phone},{label:'邮箱',children:lead.email},{label:'城市',children:lead.city},{label:'联系授权',children:lead.marketingConsent?<Tag color="green">已授权</Tag>:<Tag color="red">不可营销联系</Tag>},{label:'计划投入',children:lead.budget?`${lead.budget/10000}万元`:'待填写'},{label:'当前报价',children:lead.quoteAmount?`¥${lead.quoteAmount.toLocaleString()}`:'—'}]}/>{linkedProject&&<><Title level={5}>关联开馆方案</Title><Card size="small"style={{marginBottom:16}}><Space><Tag color={statusColor[linkedProject.status]}>{statusLabels[linkedProject.status as keyof typeof statusLabels]}</Tag><Text>{linkedProject.customerName} · {linkedProject.area}㎡ · {(linkedProject.budget/10000).toFixed(0)}万</Text></Space></Card></>}<Title level={4}>更新销售阶段</Title><Space wrap><Select value={lead.status}style={{width:150}}onChange={v=>onAction(`/leads/${lead.id}`,{status:v},'PATCH')}options={Object.entries(leadStatusLabels).map(([value,label])=>({value,label}))}/></Space><Title level={4}style={{marginTop:28}}>添加跟进记录</Title><Form form={form}layout="vertical"onFinish={v=>onAction(`/leads/${lead.id}/follow-ups`,v)}><Form.Item name="channel"label="渠道"initialValue="phone"><Select options={[['phone','电话'],['wechat','微信'],['email','邮件'],['meeting','会议']].map(([value,label])=>({value,label}))}/></Form.Item><Form.Item name="note"label="沟通记录"rules={[{required:true}]}><Input.TextArea rows={4}/></Form.Item><Form.Item name="nextAt"label="下次跟进时间"><Input type="datetime-local"/></Form.Item><Button htmlType="submit"type="primary">保存跟进</Button></Form>{follow.length>0&&<><Title level={4}style={{marginTop:28}}>历史跟进</Title>{follow.map(f=><Card key={f.id}size="small"style={{marginBottom:8}}><Tag>{f.channel}</Tag><Text>{f.note}</Text><div><Text type="secondary">{new Date(f.at).toLocaleString('zh-CN')}</Text></div></Card>)}</>}</Drawer>}

function CatalogPage({items,venues,role,onSaved}:{items:CatalogItem[];venues:VenueType[];role:Role;onSaved:()=>void}){const isAdmin=role==='admin';const[open,setOpen]=useState(false);const[form]=Form.useForm();const save=async()=>{const v=await form.validateFields();await api('/catalog',{method:'POST',body:JSON.stringify({...v,id:`item-${Date.now()}`,active:true,minArea:v.minArea||0,minBudget:v.minBudget||0,serviceTags:[],audienceTags:[],description:v.description||'',venueTypeIds:[],prototypeIds:v.prototypeIds||[]})});setOpen(false);form.resetFields();onSaved()};return <Card className="panel"title="产品规格与价格主表"extra={isAdmin&&<Button type="primary"icon={<PlusOutlined/>}onClick={()=>setOpen(true)}>新增规格</Button>}><Table rowKey="id"dataSource={items.filter(x=>x.kind==='equipment')}columns={[{title:'产品 / 规格',render:(_,x)=><><b>{x.name}</b><div className="muted">{x.specification||x.variantId}</div></>},{title:'分类',dataIndex:'category'},{title:'画册价',dataIndex:'catalogPrice',render:v=>v?`¥${v}`:'—'},{title:'历史价',dataIndex:'historicalPrice',render:v=>v?`¥${v}`:'—'},{title:'标准报价',dataIndex:'approvedPrice',render:v=>v?`¥${v}`:'—'},{title:'价格状态',dataIndex:'priceStatus',render:s=><Tag color={s==='approved'?'green':s==='conflict'?'red':'orange'}>{s==='approved'?'已审核':s==='conflict'?'冲突':'询价'}</Tag>},{title:'来源',dataIndex:'source'}]}/>{isAdmin&&<Modal open={open}onCancel={()=>setOpen(false)}onOk={save}title="新增产品规格"><Form form={form}layout="vertical"><Form.Item name="name"label="产品名称"rules={[{required:true}]}><Input/></Form.Item><Row gutter={12}><Col span={12}><Form.Item name="variantId"label="规格ID"rules={[{required:true}]}><Input/></Form.Item></Col><Col span={12}><Form.Item name="category"label="分类"rules={[{required:true}]}><Input/></Form.Item></Col></Row><Form.Item name="specification"label="规格说明"><Input/></Form.Item><Row gutter={12}><Col span={8}><Form.Item name="approvedPrice"label="标准报价"><InputNumber/></Form.Item></Col><Col span={8}><Form.Item name="floorPrice"label="审批底价"><InputNumber/></Form.Item></Col><Col span={8}><Form.Item name="catalogPrice"label="画册价"><InputNumber/></Form.Item></Col></Row></Form></Modal>}</Card>}
function VenuePage({items}:{items:VenueType[]}){return <Card className="panel"title="二级运营原型"><div className="venue-grid">{items.map(v=><Card key={v.id}><div className="venue-icon"><SettingOutlined/></div><Title level={4}>{v.name}</Title><Text type="secondary">{v.description}</Text><div><Badge status={v.active?'success':'default'}text={v.active?'正在使用':'已停用'}/></div></Card>)}</div></Card>}
export default()=> <AntApp><App/></AntApp>;
