import { BadRequestException, ForbiddenException, Injectable, NotFoundException, OnModuleDestroy, OnModuleInit, UnauthorizedException } from '@nestjs/common';
import { Pool } from 'pg';
import { capabilityScore, emptyCapability, readinessScore } from '@opening/shared';
import type { AuditEvent, CatalogItem, FollowUp, Lead, LeadStatus, OpeningProject, ProjectStatus, Role, ServiceOffering, StaffAccount, UserAccount, VenueType } from '@opening/shared';
import { catalog, venues } from './seed';
import { RulesService } from './rules.service';
import { hashPassword, verifyPassword } from './auth';
import { MailService } from './mail.service';

@Injectable()
export class StoreService implements OnModuleInit,OnModuleDestroy {
  projects:OpeningProject[]=[]; catalog:CatalogItem[]=catalog.map(x=>({...x})); venues:VenueType[]=venues.map(x=>({...x})); audits:AuditEvent[]=[];
  users:UserAccount[]=[]; staff:StaffAccount[]=[]; leads:Lead[]=[]; followUps:FollowUp[]=[];
  private codes=new Map<string,{code:string;expires:number}>(); private emailCodes=new Map<string,{code:string;expires:number}>(); private pool!:Pool;
  constructor(private rules:RulesService,private mail:MailService){}

  async onModuleInit(){
    if(!process.env.DATABASE_URL) throw new Error('DATABASE_URL is required to start the application');
    this.pool=new Pool({connectionString:process.env.DATABASE_URL});
    await this.pool.query('SELECT 1');
    const [venueRows,catalogRows,projectRows,auditRows,userRows,leadRows,staffRows]=await Promise.all([
      this.pool.query('SELECT payload FROM venue_types ORDER BY id'),
      this.pool.query('SELECT payload FROM catalog_items ORDER BY id'),
      this.pool.query('SELECT payload FROM projects ORDER BY created_at DESC'),
      this.pool.query('SELECT id,project_id,actor_id,actor_role,action,detail,created_at FROM audit_events ORDER BY created_at DESC'),
      this.pool.query('SELECT payload FROM user_accounts ORDER BY created_at DESC'),
      this.pool.query('SELECT payload FROM leads ORDER BY created_at DESC'),
      this.pool.query('SELECT id,email,password_hash,name,role,title,phone,active,created_at FROM staff_accounts ORDER BY created_at DESC')
    ]);
    if(venueRows.rowCount)this.venues=venueRows.rows.map(r=>r.payload);else await Promise.all(this.venues.map(v=>this.persistVenue(v)));
    if(catalogRows.rowCount)this.catalog=catalogRows.rows.map(r=>r.payload);else await Promise.all(this.catalog.map(i=>this.persistCatalog(i)));
    this.projects=projectRows.rows.map(r=>r.payload);
    this.users=userRows.rows.map((r:any)=>r.payload);
    this.leads=leadRows.rows.map((r:any)=>r.payload);
    this.staff=staffRows.rows.map((r:any)=>({id:r.id,email:r.email,passwordHash:r.password_hash,name:r.name,role:r.role,title:r.title,phone:r.phone,active:r.active,createdAt:new Date(r.created_at).toISOString()}));
    this.audits=auditRows.rows.map(r=>({id:r.id,projectId:r.project_id,actorId:r.actor_id,actorRole:r.actor_role,action:r.action,detail:r.detail,at:new Date(r.created_at).toISOString()}));
  }
  async onModuleDestroy(){await this.pool?.end();}

  sendCode(phone:string){if(!/^1\d{10}$/.test(phone))throw new BadRequestException('请输入有效的11位手机号');const code=String(Math.floor(100000+Math.random()*900000));this.codes.set(phone,{code,expires:Date.now()+5*60_000});return{ok:true,expiresIn:300};}
  register(input:Partial<UserAccount>&{code:string}){const record=this.codes.get(input.phone||'');if(!record||record.expires<Date.now()||record.code!==input.code)throw new UnauthorizedException('验证码无效或已过期');let user=this.users.find(x=>x.phone===input.phone);if(!user){if(!/^[^\s@]+@[^\s@]+\.[^\s@]+$/.test(input.email||''))throw new BadRequestException('请输入有效邮箱');if(!input.name||!input.city||!input.identity)throw new BadRequestException('请完整填写姓名、城市和身份');}const now=new Date().toISOString();if(user)Object.assign(user,input,{consentAt:input.marketingConsent?now:user.consentAt});else{user={id:`user-${Date.now()}`,phone:input.phone!,email:input.email!,name:input.name!,city:input.city!,identity:input.identity!,stage:input.stage||'exploring',preferredContact:input.preferredContact||'phone',contactWindow:input.contactWindow||'工作日 9:00-18:00',marketingConsent:!!input.marketingConsent,consentAt:input.marketingConsent?now:undefined,organizationId:`org-${Date.now()}`,createdAt:now};this.users.push(user);this.leads.unshift({id:`lead-${Date.now()}`,userId:user.id,name:user.name,phone:user.phone,email:user.email,city:user.city,identity:user.identity,budget:0,area:0,marketingConsent:user.marketingConsent,status:'registered',createdAt:now,updatedAt:now});}
    this.codes.delete(user.phone);void this.persistUser(user);const lead=this.leads.find(x=>x.userId===user!.id&&!x.projectId);if(lead)void this.persistLead(lead);return user;}
  user(actor:{id:string;role:Role}){const u=this.users.find(x=>x.id===actor.id);if(!u)throw new NotFoundException('账号不存在');return u;}

  async sendEmailCode(email:string){if(!/^[^\s@]+@[^\s@]+\.[^\s@]+$/.test(email))throw new BadRequestException('请输入有效的邮箱地址');const code=String(Math.floor(100000+Math.random()*900000));this.emailCodes.set(email,{code,expires:Date.now()+5*60_000});if(process.env.SMTP_USER){this.mail.sendVerificationCode(email,code).catch(()=>{});}return{ok:true,expiresIn:300};}

  registerByEmail(input:Partial<UserAccount>&{code:string;password:string}){const record=this.emailCodes.get(input.email||'');if(!record||record.expires<Date.now()||record.code!==input.code)throw new UnauthorizedException('邮箱验证码无效或已过期');if(!input.phone||!/^1\d{10}$/.test(input.phone))throw new BadRequestException('请输入有效的11位手机号');if(!input.password||input.password.length<6)throw new BadRequestException('密码至少6位');if(!input.name||!input.city||!input.identity)throw new BadRequestException('请完整填写姓名、城市和身份');const existing=this.users.find(x=>x.email===input.email);const now=new Date().toISOString();const passwordHash=hashPassword(input.password);let user:UserAccount;if(existing){user=existing;Object.assign(user,input,{passwordHash,consentAt:input.marketingConsent?now:user.consentAt});}else{user={id:`user-${Date.now()}`,phone:input.phone!,email:input.email!,name:input.name!,city:input.city!,identity:input.identity!,stage:input.stage||'exploring',preferredContact:input.preferredContact||'phone',contactWindow:input.contactWindow||'工作日 9:00-18:00',marketingConsent:!!input.marketingConsent,consentAt:input.marketingConsent?now:undefined,organizationId:`org-${Date.now()}`,createdAt:now,passwordHash,emailVerified:true};this.users.push(user);this.leads.unshift({id:`lead-${Date.now()}`,userId:user.id,name:user.name,phone:user.phone,email:user.email,city:user.city,identity:user.identity,budget:0,area:0,marketingConsent:user.marketingConsent,status:'registered',createdAt:now,updatedAt:now});}
    this.emailCodes.delete(input.email!);void this.persistUser(user);const lead=this.leads.find(x=>x.userId===user.id&&!x.projectId);if(lead)void this.persistLead(lead);return user;}

  loginByEmailCode(email:string,code:string){const record=this.emailCodes.get(email);if(!record||record.expires<Date.now()||record.code!==code)throw new UnauthorizedException('邮箱验证码无效或已过期');const user=this.users.find(x=>x.email===email);if(!user)throw new NotFoundException('该邮箱未注册，请先注册');this.emailCodes.delete(email);return user;}

  loginByEmailPassword(email:string,password:string){const user=this.users.find(x=>x.email===email) as any;if(!user)throw new NotFoundException('该邮箱未注册');if(!user.passwordHash)throw new BadRequestException('该账号未设置密码，请使用邮箱验证码登录');if(!verifyPassword(password,user.passwordHash))throw new UnauthorizedException('密码错误');return user;}

  async setEmailPassword(actor:{id:string;role:Role},password:string){if(!password||password.length<6)throw new BadRequestException('密码至少6位');const user=this.users.find(x=>x.id===actor.id) as any;if(!user)throw new NotFoundException('账号不存在');user.passwordHash=hashPassword(password);void this.persistUser(user);return{ok:true};}

  staffLogin(email:string,password:string){const s=this.staff.find(x=>x.email===email);if(!s)throw new NotFoundException('该邮箱未注册');if(!s.active)throw new ForbiddenException('账号已停用');if(!verifyPassword(password,s.passwordHash))throw new UnauthorizedException('密码错误');return s;}
  staffMe(actor:{id:string}){const s=this.staff.find(x=>x.id===actor.id);if(!s)throw new NotFoundException('账号不存在');return s;}

  list(actor:{id:string;role:Role},query=''){const pool=actor.role==='customer'?this.projects.filter(p=>p.customerId===actor.id):actor.role==='consultant'?this.projects.filter(p=>p.consultantId===actor.id):this.projects;const q=query.trim().toLowerCase();return pool.filter(p=>!q||[p.customerName,p.phone,p.city,p.venueTypeName].some(v=>v.toLowerCase().includes(q))).map(p=>this.visible(p,actor));}
  get(id:string,actor:{id:string;role:Role}){const p=this.projects.find(x=>x.id===id);if(!p)throw new NotFoundException('项目不存在');if(actor.role==='customer'&&p.customerId!==actor.id)throw new ForbiddenException('无权访问其他客户方案');if(actor.role==='consultant'&&p.consultantId!==actor.id)throw new ForbiddenException('该项目尚未分配给你');return this.visible(p,actor);}
  saveDraft(actor:{id:string;role:Role},input:Partial<OpeningProject>){if(actor.role!=='customer')throw new ForbiddenException();const current=input.id?this.projects.find(x=>x.id===input.id):undefined;if(current&&current.customerId!==actor.id)throw new ForbiddenException();const user=this.users.find(x=>x.id===actor.id);if(!user)throw new NotFoundException('请先注册账号');const now=new Date().toISOString();const readiness=input.readiness||{capital:50,resources:50,involvement:50,returnExpectation:50,riskTolerance:50};const capability={...emptyCapability(),...(input.capability||{})};const venue={address:'',area:Number(input.area)||100,rentMonthly:0,ceilingHeight:3,beds:2,...(input.venue||{})};
    const base:OpeningProject=current||{id:`project-${Date.now()}`,customerId:actor.id,organizationId:user.organizationId,customerName:user.name,phone:user.phone,email:user.email,venueTypeId:'',venueTypeName:'',city:user.city,area:venue.area,budget:0,audiences:[],plannedServices:[],openingDate:'',teamFoundation:'',readiness,readinessScore:readinessScore(readiness),capability,capabilityResult:capabilityScore(capability),quadrant:'starter',prototype:{primary:'community',alternative:'commercial',primaryReason:'',alternativeReason:'',rejectedReasons:[]},venue,renovation:{keywords:[],positioning:'',zoneRatios:[],circulation:[],essentials:[],recommended:[],deferred:[],risks:[]},licenses:[],staffing:[],quoteSummaries:[],status:'draft',recommendations:[],version:1,createdAt:now,updatedAt:now};
    Object.assign(base,input,{customerId:actor.id,organizationId:user.organizationId,customerName:user.name,phone:user.phone,email:user.email,city:input.city||user.city,area:Number(input.area||venue.area),readiness,capability,venue:{...venue,area:Number(input.area||venue.area)},status:'draft',updatedAt:now});base.readinessScore=readinessScore(base.readiness);base.capabilityResult=capabilityScore(base.capability);if(!current)this.projects.push(base);this.audit(base,actor,'SAVE_DRAFT','保存开馆测算草稿');void this.persistProject(base);return base;}

  transition(id:string,actor:{id:string;role:Role},next:ProjectStatus,detail=''){const p=this.projects.find(x=>x.id===id);if(!p)throw new NotFoundException();const allowed:Record<ProjectStatus,{roles:Role[];from:ProjectStatus[]}>= {
    draft:{roles:['customer'],from:['draft']},submitted:{roles:['customer'],from:['draft']},assigned:{roles:['admin'],from:['submitted']},planning:{roles:['consultant','admin'],from:['assigned','planning','review','published']},review:{roles:['consultant','admin'],from:['planning','review','submitted']},published:{roles:['admin'],from:['review','submitted']},foundation_confirmed:{roles:['customer','admin'],from:['published']},growth_active:{roles:['customer','admin'],from:['foundation_confirmed']}};
    const rule=allowed[next];if(!rule.roles.includes(actor.role)||!rule.from.includes(p.status))throw new BadRequestException(`不能从${p.status}变为${next}`);if(actor.role==='customer'&&p.customerId!==actor.id)throw new ForbiddenException();p.status=next;p.updatedAt=new Date().toISOString();if(next==='submitted'){this.rules.diagnose(p,this.catalog);this.syncLead(p);}if(next==='published'){p.publishedAt=new Date().toISOString();p.version+=1;this.syncLead(p);}this.audit(p,actor,`STATUS_${next.toUpperCase()}`,detail||`状态更新为${next}`);void this.persistProject(p);if(next==='published')void this.persistVersion(p);return p;}
  assign(id:string,actor:{id:string;role:Role},consultantId:string){const p=this.transition(id,actor,'assigned',`分配给顾问${consultantId}`);p.consultantId=consultantId;void this.persistProject(p);return p;}
  updatePlan(id:string,actor:{id:string;role:Role},input:Partial<OpeningProject>){const p=this.projects.find(x=>x.id===id);if(!p)throw new NotFoundException();if(actor.role==='consultant'&&p.consultantId!==actor.id)throw new ForbiddenException('只能编辑分配给自己的项目');if(!['assigned','planning','published','review'].includes(p.status))throw new BadRequestException('当前状态不可编辑');Object.assign(p,input,{status:'planning',updatedAt:new Date().toISOString()});this.rules.diagnose(p,this.catalog);this.audit(p,actor,'UPDATE_PLAN','调整方案与报价');void this.persistProject(p);return p;}
  updateServices(id:string,actor:{id:string;role:Role},services:ServiceOffering[]){const p=this.projects.find(x=>x.id===id);if(!p)throw new NotFoundException();if(actor.role==='customer'&&p.customerId!==actor.id)throw new ForbiddenException();if(!['customer','admin','consultant'].includes(actor.role))throw new ForbiddenException();if(!Array.isArray(services)||!services.length)throw new BadRequestException('至少保留一个项目');p.servicePortfolio=services.map(x=>({...x,unitPrice:Math.max(0,Number(x.unitPrice)||0),sessions:Math.max(1,Number(x.sessions)||1),monthlyTarget:Math.max(0,Number(x.monthlyTarget)||0)}));p.updatedAt=new Date().toISOString();this.rules.diagnose(p,this.catalog);p.version+=1;this.syncLead(p);this.audit(p,actor,'UPDATE_SERVICES','调整项目组合并重新计算设备报价和盈亏平衡');void this.persistProject(p);return this.visible(p,actor);}

  listLeads(actor:{id:string;role:Role},query=''){if(actor.role==='customer')throw new ForbiddenException();const pool=actor.role==='consultant'?this.leads.filter(l=>l.assignedConsultantId===actor.id):this.leads;const q=query.toLowerCase();return pool.filter(l=>!q||[l.name,l.phone,l.city,l.email].join('').toLowerCase().includes(q));}
  assignLead(id:string,actor:{id:string;role:Role},consultantId:string){if(actor.role!=='admin')throw new ForbiddenException();const lead=this.leads.find(x=>x.id===id);if(!lead)throw new NotFoundException();lead.assignedConsultantId=consultantId;lead.status=lead.projectId?'quoted':'unassigned';lead.updatedAt=new Date().toISOString();const p=lead.projectId?this.projects.find(x=>x.id===lead.projectId):undefined;if(p)p.consultantId=consultantId;void this.persistLead(lead);if(p)void this.persistProject(p);return lead;}
  updateLead(id:string,actor:{id:string;role:Role},input:Partial<Lead>){const l=this.leads.find(x=>x.id===id);if(!l)throw new NotFoundException();if(actor.role==='consultant'&&l.assignedConsultantId!==actor.id)throw new ForbiddenException();if(!['consultant','admin'].includes(actor.role))throw new ForbiddenException();Object.assign(l,input,{updatedAt:new Date().toISOString()});void this.persistLead(l);return l;}
  addFollowUp(id:string,actor:{id:string;role:Role},input:Pick<FollowUp,'channel'|'note'|'nextAt'>){const l=this.leads.find(x=>x.id===id);if(!l)throw new NotFoundException();if(actor.role==='consultant'&&l.assignedConsultantId!==actor.id)throw new ForbiddenException();if(!['consultant','admin'].includes(actor.role))throw new ForbiddenException();const f:FollowUp={id:`follow-${Date.now()}`,leadId:id,consultantId:actor.id,...input,at:new Date().toISOString()};this.followUps.unshift(f);l.lastNote=input.note;l.nextFollowUpAt=input.nextAt;l.status=l.status==='unassigned'||l.status==='quoted'?'contacted':l.status;l.updatedAt=f.at;return f;}
  leadFollowUps(id:string,actor:{id:string;role:Role}){const l=this.leads.find(x=>x.id===id);if(!l)throw new NotFoundException();if(actor.role==='consultant'&&l.assignedConsultantId!==actor.id)throw new ForbiddenException();return this.followUps.filter(x=>x.leadId===id);}
  upsertCatalog(actor:{id:string;role:Role},item:CatalogItem){if(actor.role!=='admin')throw new ForbiddenException();if(item.approvedPrice!==undefined&&item.floorPrice!==undefined&&item.approvedPrice<item.floorPrice)throw new BadRequestException('标准报价不能低于审批底价');const i=this.catalog.findIndex(x=>x.id===item.id);if(i>=0)this.catalog[i]=item;else this.catalog.push({...item,id:item.id||`item-${Date.now()}`});void this.persistCatalog(item);return item;}
  upsertVenue(actor:{id:string;role:Role},item:VenueType){if(actor.role!=='admin')throw new ForbiddenException();const i=this.venues.findIndex(x=>x.id===item.id);if(i>=0)this.venues[i]=item;else this.venues.push({...item,id:item.id||`venue-${Date.now()}`});void this.persistVenue(item);return item;}

  private syncLead(p:OpeningProject){let l=this.leads.find(x=>x.projectId===p.id)||this.leads.find(x=>x.userId===p.customerId&&!x.projectId);const now=new Date().toISOString();const quote=p.quoteSummaries.find(x=>x.tier==='standard')?.total||0;if(!l){l={id:`lead-${Date.now()}`,userId:p.customerId,projectId:p.id,name:p.customerName,phone:p.phone,email:p.email||'',city:p.city,identity:this.users.find(x=>x.id===p.customerId)?.identity||'investor',budget:p.budget,area:p.area,marketingConsent:!!this.users.find(x=>x.id===p.customerId)?.marketingConsent,status:'quoted',createdAt:now,updatedAt:now};this.leads.unshift(l);}Object.assign(l,{projectId:p.id,budget:p.budget,area:p.area,openingDate:p.openingDate,quadrant:p.quadrant,prototype:p.prototype.primary,quoteAmount:quote,status:p.status==='draft'?'registered':p.status==='submitted'?'quoted':l.status,updatedAt:now});void this.persistLead(l);}
  private visible(p:OpeningProject,actor:{id:string;role:Role}){if(actor.role!=='customer')return p;const{interviewNotes,...safe}=p;return{...safe,interviewNotes:undefined};}
  private audit(p:OpeningProject,actor:{id:string;role:Role},action:string,detail:string){const event={id:`audit-${Date.now()}-${Math.random()}`,projectId:p.id,actorId:actor.id,actorRole:actor.role,action,detail,at:new Date().toISOString()};this.audits.unshift(event);void this.persistAudit(event);}
  private async persistProject(p:OpeningProject){await this.pool.query('INSERT INTO projects(id,customer_id,payload,status,consultant_id,version,created_at,updated_at) VALUES($1,$2,$3,$4,$5,$6,$7,$8) ON CONFLICT(id) DO UPDATE SET payload=EXCLUDED.payload,status=EXCLUDED.status,consultant_id=EXCLUDED.consultant_id,version=EXCLUDED.version,updated_at=EXCLUDED.updated_at',[p.id,p.customerId,p,p.status,p.consultantId||null,p.version,p.createdAt,p.updatedAt]);}
  private async persistUser(u:UserAccount){await this.pool.query('INSERT INTO user_accounts(id,phone,payload,created_at) VALUES($1,$2,$3,$4) ON CONFLICT(id) DO UPDATE SET payload=EXCLUDED.payload',[u.id,u.phone,u,u.createdAt]);}
  private async persistLead(l:Lead){await this.pool.query('INSERT INTO leads(id,user_id,project_id,payload,status,assigned_consultant_id,created_at,updated_at) VALUES($1,$2,$3,$4,$5,$6,$7,$8) ON CONFLICT(id) DO UPDATE SET payload=EXCLUDED.payload,status=EXCLUDED.status,assigned_consultant_id=EXCLUDED.assigned_consultant_id,updated_at=EXCLUDED.updated_at',[l.id,l.userId,l.projectId||null,l,l.status,l.assignedConsultantId||null,l.createdAt,l.updatedAt]);}
  private async persistCatalog(i:CatalogItem){await this.pool.query('INSERT INTO catalog_items(id,kind,payload,active) VALUES($1,$2,$3,$4) ON CONFLICT(id) DO UPDATE SET kind=EXCLUDED.kind,payload=EXCLUDED.payload,active=EXCLUDED.active',[i.id,i.kind,i,i.active]);}
  private async persistVenue(v:VenueType){await this.pool.query('INSERT INTO venue_types(id,payload,active) VALUES($1,$2,$3) ON CONFLICT(id) DO UPDATE SET payload=EXCLUDED.payload,active=EXCLUDED.active',[v.id,v,v.active]);}
  private async persistAudit(a:AuditEvent){await this.pool.query('INSERT INTO audit_events(id,project_id,actor_id,actor_role,action,detail,created_at) VALUES($1,$2,$3,$4,$5,$6,$7) ON CONFLICT(id) DO NOTHING',[a.id,a.projectId,a.actorId,a.actorRole,a.action,a.detail,a.at]);}
  private async persistVersion(p:OpeningProject){await this.pool.query('INSERT INTO project_versions(id,project_id,version,snapshot) VALUES($1,$2,$3,$4)',[`version-${p.id}-${p.version}`,p.id,p.version,p]);}
  private async persistStaff(s:StaffAccount){await this.pool.query('INSERT INTO staff_accounts(id,email,password_hash,name,role,title,phone,active,created_at) VALUES($1,$2,$3,$4,$5,$6,$7,$8,$9) ON CONFLICT(id) DO UPDATE SET email=EXCLUDED.email,password_hash=EXCLUDED.password_hash,name=EXCLUDED.name,role=EXCLUDED.role,title=EXCLUDED.title,phone=EXCLUDED.phone,active=EXCLUDED.active',[s.id,s.email,s.passwordHash,s.name,s.role,s.title,s.phone,s.active,s.createdAt]);}
}
