import { describe, expect, it } from 'vitest';
import { capabilityScore, emptyCapability, readinessBand, readinessScore } from '@opening/shared';
import { RulesService } from '../src/rules.service';
import { catalog, demoProject } from '../src/seed';
describe('规则与准备度',()=>{
  it('五维等权计算并分级',()=>{expect(readinessScore({capital:100,resources:80,involvement:60,returnExpectation:40,riskTolerance:20})).toBe(60);expect(readinessBand(59)).toBe('准备不足');expect(readinessBand(60)).toBe('有条件推进');expect(readinessBand(80)).toBe('准备充分');});
  it('按运营原型、面积、预算和标签生成已审核报价',()=>{const rules=new RulesService();const project=rules.diagnose({...demoProject},catalog);const result=project.recommendations;expect(result.some(x=>x.name==='三段式电动手法PT床'&&x.priceStatus==='approved')).toBe(true);expect(project.quoteSummaries.find(x=>x.tier==='standard')!.total).toBeGreaterThan(0);});
  it('停用产品不进入新方案',()=>{const result=new RulesService().match(demoProject,catalog.map(x=>({...x,active:false})));expect(result).toHaveLength(0);});
  it('四种专业/商业组合进入正确成长象限',()=>{const base=emptyCapability();expect(capabilityScore({...base,professionalBackground:80,assessmentIntervention:80,riskRecognition:80,cases:80,teachingTeam:80,customerResources:30,contentAcquisition:30,salesConversion:30,management:30,fundingTeam:30}).quadrant).toBe('expert');expect(capabilityScore({...base,professionalBackground:30,assessmentIntervention:30,riskRecognition:30,cases:30,teachingTeam:30,customerResources:80,contentAcquisition:80,salesConversion:80,management:80,fundingTeam:80}).quadrant).toBe('growth');});
  it('专业条件不足时不把医健协同作为备选',()=>{const project=new RulesService().diagnose({...demoProject,area:120,budget:400000,capability:{...emptyCapability(),professionalBackground:50,assessmentIntervention:50,riskRecognition:50,cases:50,teachingTeam:50,customerResources:50,contentAcquisition:50,salesConversion:50,management:50,fundingTeam:50}},catalog);expect(project.prototype.primary).toBe('community');expect(project.prototype.alternative).toBe('commercial');expect(project.prototype.alternativeReason).toContain('中长期升级');expect(project.prototype.rejectedReasons.join('')).toContain('医健协同店暂不作为首选');});
  it('其他描述会参与后台能力判断',()=>{const project=new RulesService().diagnose({...demoProject,capability:{...emptyCapability()},capabilityModes:{professionalBackground:'other'},capabilityNotes:{professionalBackground:'从业多年，可以独立完成并负责过团队带教'}},catalog);expect(project.capability.professionalBackground).toBeGreaterThanOrEqual(75);});
  it('按综合贡献毛利率计算盈亏平衡与安全营业额',()=>{const project=new RulesService().diagnose({...demoProject,servicePortfolio:undefined},catalog);const b=project.breakEven!;expect(b.breakEvenRevenue).toBe(Math.ceil(b.monthlyFixedCost/b.contributionMarginRate/100)*100);expect(b.safetyRevenue).toBeGreaterThan(b.breakEvenRevenue);expect(b.requiredSessions).toBeGreaterThan(0);expect(b.capacitySessions).toBeGreaterThan(0);});
});
